# coding=utf-8
from flask import Flask, redirect, url_for, request, render_template
import pandas as pd
import numpy as np
import pickle

app = Flask(__name__)
model = pickle.load(open('/home/maerion/mysite/model/Venta_casas_model.sav', 'rb'))

#............................................................

@app.route('/', methods=['GET','POST'])
def Search(model=model):
    if request.method == 'GET':
        return render_template('index.html')
    else:
        var = [
        {'Duplex':0,
    	 'Casa':1,
      	 'Departamento':2},
     	{'Central': 8,
         'Cerro-Argüello': 2,
         'Este': 3,
         'Guiñazú': 10,
         'Nordeste': 9,
         'Noroeste': 4,
         'Norte': 7,
         'Oeste': 6,
         'Sudeste': 1,
         'Sudoeste': 5,
         'Sur': 0},
 	    {'1 de Mayo': 251,
         '20 de Junio': 228,
          'ATE': 69,
          'Acosta': 174,
          'Aeronáutico': 235,
          'Alameda': 102,
          'Alberdi': 77,
          'Alberto': 218,
          'Alejandro Centeno': 129,
          'Alta Córdoba': 15,
          'Altamira': 133,
          'Alto Alberdi': 20,
          'Alto Palermo': 99,
          'Alto Verde': 25,
          'Altos de La Calera': 125,
          'Altos de Manantiales': 68,
          'Altos de San Martín': 28,
          'Altos de Villa Cabrera': 106,
          'Altos de Vélez Sársfield': 52,
          'Altos del Chateau': 181,
          'Ameghino Norte': 267,
          'Ameghino Sud': 195,
          'Amp. Res. America': 185,
          'Ampliación Jardín Espinosa': 319,
          'Ampliación Pueyrredón': 241,
          'Ampliación Residencial América': 323,
          'Argüello': 5,
          'Argüello Norte': 190,
          'Avenida': 151,
          'Ayacucho': 36,
          'Ayres del Sur': 284,
          'Bajo Galán': 287,
          'Bajo General Paz': 293,
          'Bella Vista': 197,
          'Bialet Massé': 120,
          'Brigadier San Martín': 310,
          'Cabo Farina': 187,
          'Caseros': 240,
          'Casonas Del Sur': 275,
          'Cañuelas': 191,
          'Centenario': 160,
          'Centro': 118,
          'Centro América': 149,
          'Cerro Chico': 98,
          'Cerro Norte': 214,
          'Cerro de las Rosas': 62,
          'Cerveceros': 212,
          'Chacra Escondida': 165,
          'Chacra del Norte': 13,
          'Chacra del Sur': 79,
          'Chacras de la Villa': 35,
          'Chateau Carreras': 85,
          'Cinco Lomas': 74,
          'Ciudadela': 127,
          'Claros del Bosque': 0,
          'Cofico': 24,
          'Colinas de Vélez Sársfield': 43,
          'Colinas del Cerro': 144,
          'Colonia Lola': 297,
          'Colón': 146,
          'Comarca de Allende': 16,
          'Condor Alto': 179,
          'Crisol Norte': 139,
          'Crisol Sud': 55,
          'Cuatro Hojas': 38,
          'Cuesta Colorada': 39,
          'Cumbres de Villa Allende': 270,
          'Cumbres del Golf': 101,
          'Córdoba 5': 280,
          'Docta': 97,
          'Ducasse': 245,
          'Déan Funes': 219,
          'Ejército Argentino': 296,
          'El Bosque': 206,
          'El Cabildo': 210,
          'El Refugio': 111,
          'El Rodeo': 17,
          'El Talar de Mendiolaza': 112,
          'El Trebol': 123,
          'Empalme': 107,
          'Escobar': 29,
          'Estación Flores': 303,
          'Estancia Q2': 161,
          'Ferreyra': 200,
          'Ferroviario Mitre': 140,
          'Fincas Del Sur II': 78,
          'Fincas del Sur I': 73,
          'General Artigas': 256,
          'General Belgrano': 299,
          'General Bustos': 72,
          'General Paz': 6,
          'General Pueyrredón': 116,
          'Golf': 18,
          'Granadero Pringles': 265,
          'Granja de Funes': 84,
          'Greenville 2': 1,
          'Guayaquil': 259,
          'Guiñazú': 307,
          'Güemes': 82,
          'Hipólito Yrigoyen': 207,
          'Hogar Propio': 269,
          'Inaudi': 145,
          'Industrial Este': 236,
          'Iponá': 138,
          'Irupé': 264,
          'Ituzaingó': 268,
          'Jardines del Jockey': 158,
          'Jardín': 37,
          'Jardín Claret': 81,
          'Jardín Espinosa': 33,
          'Jardín Hipódromo': 302,
          'Jardín de los Boulevares': 178,
          'Jardín del Pilar': 142,
          'Jardín del Sud': 271,
          'Jerónimo Luis de Cabrera': 231,
          'José Hernández': 225,
          'José Ignacio Díaz': 83,
          'Juan B. Justo': 258,
          'Juan XXIII': 86,
          'Juniors': 63,
          'Kennedy': 248,
          'La Calandria': 147,
          'La Calera': 274,
          'La Carolina': 80,
          'La Cascada': 300,
          'La Catalina': 57,
          'La Cuesta': 12,
          'La Estanzuela': 59,
          'La France': 205,
          'La Herradura': 257,
          'La Morada': 110,
          'La Paloma': 88,
          'La Paya I': 94,
          'La Paya II': 45,
          'La Reserva': 153,
          'La Rufina': 14,
          'La Salle': 176,
          'La Santina': 175,
          'Lamadrid': 216,
          'Las Cañitas': 67,
          'Las Corzuelas': 286,
          'Las Dalias': 201,
          'Las Delicias': 292,
          'Las Flores': 70,
          'Las Lilas': 217,
          'Las Magnolias': 183,
          'Las Margaritas': 203,
          'Las Palmas': 71,
          'Las Rosas': 104,
          'Las Violetas': 301,
          'Liceo General Paz': 56,
          'Lomas Este': 40,
          'Lomas de San Martín': 132,
          'Lomas de la Carolina': 65,
          'Lomas del Chateau': 114,
          'Lomas del Suquía': 224,
          'Los Boulevares': 61,
          'Los Ceibos': 285,
          'Los Gigantes': 128,
          'Los Granados': 234,
          'Los Naranjos': 92,
          'Los Olmos': 202,
          'Los Olmos Sud': 220,
          'Los Paraísos': 199,
          'Los Pinos': 306,
          'Los Plátanos': 105,
          'Los Prados': 221,
          'Los Robles': 192,
          'Los Sauces': 291,
          'Los Álamos': 304,
          'Maipú': 281,
          'Maipú Sección 1': 103,
          'Maipú Sección 2': 2,
          'Malagueño': 278,
          'Manantiales': 4,
          'Marcos Sastre': 208,
          'Marechal': 252,
          'Mariano Balcarce': 260,
          'Mariano Fragueiro': 182,
          'Marqués de Sobremonte': 60,
          'Matienzo': 11,
          'Mauller': 313,
          'Mendiolaza': 273,
          'Mendiolaza Golf': 108,
          'Mercantil': 311,
          'Mirador': 227,
          'Miradores de Manantiales': 31,
          'Miralta': 315,
          'Nueva Córdoba': 19,
          'Nueva Italia': 155,
          'Nuevo Urca': 119,
          'Observatorio': 136,
          'Otro': 3,
          'Oña': 250,
          'Padre Claret': 159,
          'Palermo Bajo': 32,
          'Palmar': 309,
          'Palmas de Claret': 21,
          'Panamericano': 131,
          'Parque Alameda': 289,
          'Parque Atlántica': 156,
          'Parque Capital': 163,
          'Parque Capital Sud': 246,
          'Parque Chacabuco': 87,
          'Parque Don Bosco': 117,
          'Parque Futura': 325,
          'Parque Gorema': 121,
          'Parque Horizonte': 9,
          'Parque Jorge Newbery': 150,
          'Parque Latino': 226,
          'Parque Liceo Sección 3': 288,
          'Parque Los Molinos': 126,
          'Parque Montecristo': 30,
          'Parque Republica': 211,
          'Parque San Carlos': 124,
          'Parque Sarmiento': 290,
          'Parque Vélez Sársfield': 47,
          'Paso de los Andes': 91,
          'Patria': 242,
          'Patricios': 154,
          'Poeta Lugones': 50,
          'Pque. Liceo I': 166,
          'Primera Junta': 209,
          'Providencia': 172,
          'Puente Blanco': 263,
          'Quebrada de las Rosas': 34,
          'Quinta Santa Ana': 189,
          'Quintas de Argüello': 58,
          'Quisquisacate': 308,
          'Ramón J. Cárcano': 168,
          'Remedios de Escalada': 318,
          'Renacimiento': 316,
          'Res. Sud': 244,
          'Res. Vélez Sársfield': 53,
          'Residencial América': 277,
          'Residencial Chateau': 314,
          'Residencial Olivos': 222,
          'Residencial San Carlos': 276,
          'Residencial San Roque': 324,
          'Residencial Santa Ana': 198,
          'Residencial Sud': 317,
          'Residencial Vélez Sársfield': 282,
          'Riberas de Manantiales': 95,
          'Rivadavia': 266,
          'Rivera Indarte': 164,
          'Rogelio Martinez': 76,
          'Rosedal': 134,
          'SMATA': 113,
          'San Alfonso del Talar': 46,
          'San Antonio': 249,
          'San Cayetano': 295,
          'San Daniel': 173,
          'San Felipe': 262,
          'San Fernando': 96,
          'San Francisco': 130,
          'San Ignacio': 247,
          'San Isidro': 75,
          'San Javier': 238,
          'San José': 66,
          'San Lorenzo': 204,
          'San Martín': 89,
          'San Martín Norte': 321,
          'San Nicolás': 230,
          'San Pablo': 169,
          'San Rafael': 184,
          'San Salvador': 64,
          'San Vicente': 148,
          'Santa Cecilia': 312,
          'Santa Clara de Asís': 115,
          'Santa Isabel': 180,
          'Santa Rita': 141,
          'Santa Rosa': 109,
          'Santina Norte': 48,
          'Sargento Cabral': 223,
          'Sarmiento': 215,
          'Siete Soles': 93,
          'Solares de San Alfonso': 152,
          'Solares de Santa María': 10,
          'Suárez': 283,
          'Tablada Park': 54,
          'Talleres Este': 135,
          'Talleres Oeste': 167,
          'Talleres Sud': 243,
          'Tejas III': 41,
          'Tejas del Sur I': 44,
          'Tejas del Sur II': 51,
          'Teniente Benjamín Matienzo': 253,
          'Terranova': 170,
          'Terrazas de La Estanzuela': 143,
          'Terrazas de Villa Allende': 162,
          'UOCRA': 171,
          'Urca': 7,
          'Urquiza': 255,
          'Valle Cercano': 279,
          'Valle Escondido': 23,
          'Valle del Golf': 294,
          'Valle del Sol': 157,
          'Vicor': 298,
          'Villa Adela': 194,
          'Villa Alberdi': 239,
          'Villa Allende': 42,
          'Villa Allende Parque': 49,
          'Villa Argentina': 100,
          'Villa Azalais': 232,
          'Villa Belgrano': 27,
          'Villa Bustos': 320,
          'Villa Cabrera': 26,
          'Villa Corina': 233,
          'Villa Cornu': 196,
          'Villa Coronel Olmedo': 188,
          'Villa El Libertador': 193,
          'Villa Esquiú': 186,
          'Villa General Urquiza': 322,
          'Villa Gran Parque': 229,
          'Villa Los Angeles': 237,
          'Villa Marta': 90,
          'Villa Páez': 305,
          'Villa Revol': 254,
          'Villa Rivera Indarte': 122,
          'Villa San Carlos': 272,
          'Villa Warcalde': 22,
          'Yapeyú': 177,
          'Yofre I': 261,
          'Yofre Norte': 213,
          'Yofre Sud': 137,
          'Zumaran': 8},
    	{'Abierto': 2,
    	 'Cerrado': 0,
    	 'Con Seguridad': 1,
    	 'Country': 3},
    	]

        propiedad = int(var[0][request.form['propiedad']])
        zona = int(var[1][request.form['zona']])
        if not request.form['barrio'] in var[2]:
            barrio = int(var[2]['Otro'])
        else:
            barrio = int(var[2][request.form['barrio']])
        tipobarrio = int(var[3][request.form['tipobarrio']])
        dormitorios = int(request.form['dormitorios'])
        banios = int(request.form['banios'])
        cocheras = int(request.form['cocheras'])
        mst2C = np.log1p(float(request.form['mst2C']))
        mst2T = np.log1p(float(request.form['mst2T']))

        col = ['Tipo de Propiedad', 'Zona', 'Barrio', 'Tipo de Barrio',
               'Cantidad de Dormitorios', 'Cantidad de Baños', 'Cantidad de Cocheras',
               'Superficie Cubierta m2', 'Superficie Total m2', 'Zona_was_missing',
               'Barrio_was_missing', 'Tipo de Barrio_was_missing',
               'Cantidad de Dormitorios_was_missing', 'Cantidad de Baños_was_missing',
               'Cantidad de Cocheras_was_missing','Superficie Cubierta m2_was_missing',
               'Superficie Total m2_was_missing',
              ]

        row =[[propiedad,zona,barrio,
              tipobarrio,dormitorios,
              banios,cocheras,mst2C,mst2T,
              False,False,False,False,False,False,False,False]]

        inp = pd.DataFrame(row, columns=col)

        predict = "{:,.2f}".format( int(model.predict(inp)[0]) )

        return render_template('index.html', _anchor="search", result=predict)

#............................................................

if __name__ == '__main__':
    app.run(debug = True)